apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modeldeployments.ml.example.com
spec:
  group: ml.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - modelName
            - modelVersion
            properties:
              modelName:
                type: string
                description: "Name of the model in the registry"
              modelVersion:
                type: integer
                description: "Version of the model to deploy"
              replicas:
                type: integer
                default: 1
                minimum: 1
                maximum: 10
                description: "Number of inference server replicas"
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      memory:
                        type: string
                        default: "256Mi"
                      cpu:
                        type: string
                        default: "250m"
                  limits:
                    type: object
                    properties:
                      memory:
                        type: string
                        default: "512Mi"
                      cpu:
                        type: string
                        default: "500m"
              environment:
                type: string
                enum: ["development", "staging", "production"]
                default: "development"
                description: "Target environment for deployment"
              autoscaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  minReplicas:
                    type: integer
                    default: 1
                    minimum: 1
                  maxReplicas:
                    type: integer
                    default: 5
                    minimum: 1
                  targetCPUUtilizationPercentage:
                    type: integer
                    default: 70
                    minimum: 1
                    maximum: 100
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Updating"]
                description: "Current phase of the deployment"
              replicas:
                type: integer
                description: "Current number of replicas"
              readyReplicas:
                type: integer
                description: "Number of ready replicas"
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              deploymentName:
                type: string
                description: "Name of the created Deployment"
              serviceName:
                type: string
                description: "Name of the created Service"
              lastUpdated:
                type: string
                format: date-time
                description: "Last time the deployment was updated"
    additionalPrinterColumns:
    - name: Model
      type: string
      description: Model Name
      jsonPath: .spec.modelName
    - name: Version
      type: integer
      description: Model Version
      jsonPath: .spec.modelVersion
    - name: Replicas
      type: integer
      description: Number of Replicas
      jsonPath: .spec.replicas
    - name: Phase
      type: string
      description: Deployment Phase
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: modeldeployments
    singular: modeldeployment
    kind: ModelDeployment
    shortNames:
    - mldeploy
    - md