apiVersion: v1
kind: Namespace
metadata:
  name: ml-platform
  labels:
    name: ml-platform
    purpose: ml-model-serving
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-platform-config
  namespace: ml-platform
data:
  POSTGRES_DB: "mlplatform"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MODEL_BUCKET: "models"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  ENVIRONMENT: "kubernetes"
  LOG_LEVEL: "INFO"